name: reviewdog_demo
on: pull_request
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Grant permission for gradlew
        run: chmod +x ./gradlew
      - name: Run spotBugsMain
        run: ./gradlew spotBugsMain
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.17.2
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          cat ./build/reports/spotbugs/main.sarif 
          | reviewdog -f sarif -reporter=github-pr-review -name run-reviewdog -tee